name: Wunengzi
favicon: null
layout_spectrum: 0.722128
typography_spectrum: 0.508445
title: Wunengzi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C8C0C0'
    - '#5A2F2B'
    - '#809098'
    - '#985048'
    - '#000000'
  brandStrength: 0.440103
  lightness: 0.843113
  saturation: 0.255855
  rhythmicContrast: 0.274622
purpose: []
