name: Wunengzi
favicon: null
layout_spectrum: 0.722128
typography_spectrum: 0.508445
title: Wunengzi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#98d3cf'
    - '#639e9a'
    - '#00302d'
    - '#286663'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
