analytics: {}
color:
  brandColors:
    - '#C8C0C0'
    - '#5A2F2B'
    - '#809098'
    - '#985048'
    - '#000000'
  brandStrength: 0.440103
  lightness: 0.843113
  rhythmicContrast: 0.274622
  saturation: 0.255855
cta: {}
layout_spectrum: 0.722128
name: Wunengzi
opengraph: {}
purpose: []
typography_spectrum: 0.508445
